export const ActionTypes = {
    FETCH_BRANDS_REQUEST: 'FETCH_BRANDS_REQUEST',
    FETCH_BRANDS_SUCCESS: 'FETCH_BRANDS_SUCCESS',
    FETCH_BRANDS_FAILURE: 'FETCH_BRANDS_FAILURE',

    FETCH_BRAND_REQUEST: 'FETCH_BRAND_REQUEST',
    FETCH_BRAND_SUCCESS: 'FETCH_BRAND_SUCCESS',
    FETCH_BRAND_FAILURE: 'FETCH_BRAND_FAILURE',

    CREATE_BRAND_REQUEST: 'CREATE_BRAND_REQUEST',
    CREATE_BRAND_SUCCESS: 'CREATE_BRAND_SUCCESS',
    CREATE_BRAND_FAILURE: 'CREATE_BRAND_FAILURE',

    UPDATE_BRAND_REQUEST: 'UPDATE_BRAND_REQUEST',
    UPDATE_BRAND_SUCCESS: 'UPDATE_BRAND_SUCCESS',
    UPDATE_BRAND_FAILURE: 'UPDATE_BRAND_FAILURE',

    DELETE_BRAND_REQUEST: 'DELETE_BRAND_REQUEST',
    DELETE_BRAND_SUCCESS: 'DELETE_BRAND_SUCCESS',
    DELETE_BRAND_FAILURE: 'DELETE_BRAND_FAILURE',
  };
  